# Generated by Django 4.1.2 on 2022-11-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.IntegerField(unique=True)),
                ('mail', models.EmailField(max_length=100)),
                ('comments', models.TextField(max_length=256)),
                ('parent_selection', models.CharField(max_length=20)),
                ('child_selection', models.CharField(max_length=20)),
                ('user_interest', models.CharField(max_length=20)),
            ],
        ),
    ]
