# Generated by Django 4.1.2 on 2022-11-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
